---
- name: install and start apache2 service
  hosts: demo
  gather_facts: yes
  become: yes
  tasks:
    - name: install the apache2 service
      apt:
        name: apache2
        state: present

    - name: start the apache2 service
      service:
        name: apache2
        state: started
